services:
  fantasy_trades_web_app:
    container_name: fantasy_trades_web_app
    volumes:
      - ./src:/usr/share/nginx/html
      - ./public:/app/public
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  app: