services:
  fantasy_trades_web_app:
    container_name: fantasy_trades_web_app
    volumes:
      - app:/usr/share/nginx/html
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  app: